### PR TITLE
bump libocr; add context

### PR DESCRIPTION
**Pull request by jmank88**
https://smartcontract-it.atlassian.net/browse/BCF-2887

Supports:
- https://github.com/smartcontractkit/chainlink/pull/14011

### CODE REVIEW

**Comment by coventry** [comment]
Why is there such a large increase in the `go.work.sum` file?

**Review by coventry — COMMENTED** [review]
I can approve this PR, if we can identify the source of the increased dependencies in the `sum` file.

**Comment by jmank88** [comment]
I think the go.work.sum is just growing from working in a local workspace and no tidy command to clean it up - but it has no effect on the build since these are just checksums for reference.

**Review by coventry — APPROVED** [review]
Great, SGTM.

**Pull request merged**
